services:
  - type: web
    name: rocket-flask
    plan: starter
    env: python
    region: frankfurt  # region should be same as your database region.
    buildCommand: "./build.sh"
    startCommand: "gunicorn apps:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
